### ISSUE TITLE
create a contact block

### ISSUE THREAD

**Issue by vitalii-kushnirenko** [vitalii-kushnirenko/WebResume#4]
Links to social networks (Facebook or Instagram, etc.), phone number or e-mail address, etc. Maybe not all the links in the world, but only those that are really relevant.

**Comment by katya-pidpala** [comment]
Contact
Kharkiv, Ukraine
Mobile: (068)-564-22-26
Email: kushnirenkovitalii@gmail.com
LinkedIn: https://www.linkedin.com/in/vitalii-kushnirenko-47295a219/
Git: https://github.com/vitalii-kushnirenko
Bitbucet:
