### ISSUE TITLE
make a block of skills

### ISSUE THREAD

**Issue by vitalii-kushnirenko** [vitalii-kushnirenko/WebResume#5]
write about your skills

**Comment by katya-pidpala** [comment]
SKILLS
- Java Core, Collections, Stream
- Spring(Boot, Core, MVC, JPA, JDBC)
- Hibernate
- SQL(Postgres, MongoDB)
- Git, GitHub
- HTML, CSS, JS, Angular
- Junit, Mocktico
- Maven
- REST, SOAP
-  RabbitMQ/Kafka
- CI/CD, AWS 
- Docer
- Intellij IDEA, Visual Code 
- YouTrack
