### ISSUE TITLE
make up a block of study

### ISSUE THREAD

**Issue by vitalii-kushnirenko** [vitalii-kushnirenko/WebResume#8]
write about your experience of studying at the university and courses (if any)

**Comment by katya-pidpala** [comment]
EDUCATION
Ukrainian State Engineering Pedagogical Academy, Kharkiv 
2020-2021
Master's degree, Professional education. Electronics, metrology and radio telecommunications.
National Aerospace University -'Kharkiv Aviation Institute'​
2016-2020
Bachelor's degree, Computer Engineering

10.09.2021 – 10.10.2021 NixEducation Online 
25.08.2021 – 06.10.2021 SoftServe Java Crash Course
